version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    target-branch: "dev"
    open-pull-requests-limit: 10
    reviewers:
      - BMTLab
    labels:
      - dependencies
      - npm
    assignees:
      - BMTLab

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    target-branch: "dev"
    open-pull-requests-limit: 10
    reviewers:
      - BMTLab
    labels:
      - dependencies
      - github-actions
    assignees:
      - BMTLab
