version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    target-branch: "dev"
    open-pull-requests-limit: 10
    reviewers:
      - BMTLab
    labels:
      - dependencies
      - npm
    assignees:
      - BMTLab
    ignore:
      - dependency-name: "eslint"
        versions: [ "8.57.x" ]
      - dependency-name: "eslint-plugin-n"
        versions: [ "16.6.x" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    target-branch: "dev"
    open-pull-requests-limit: 10
    reviewers:
      - BMTLab
    labels:
      - dependencies
      - github-actions
    assignees:
      - BMTLab
