# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/metadata-syntax-for-github-actions

name: 'NuGet Package Availability Checker'
description: >-
  GitHub Action automates NuGet package availability checks, ensuring packages exist and are indexed on nuget.org.
author: 'BMTLab'
branding:
  icon: activity
  color: blue
inputs:
  package:
    description: 'NuGet package name to check'
    required: true
  version:
    description: 'Package version to check'
    required: true
  attempts:
    description: 'Maximum number of attempts to check the package availability'
    required: false
    default: '1'
runs:
  using: 'node20'
  main: 'src/index.js'
