# ./actions/setup-node-project/action.yml
name: Setup Node.js with Cache and Install Dependencies
description: >-
  Checkout, setup Node.js, cache node_modules, and install dependencies
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      run: echo 'Dependencies reinstalled after cache failure'
      with:
        node-version-file: .nvmrc

    - name: Cache Node.js modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-build-${{ hashFiles('package.json', 'package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ hashFiles('package.json') }}-

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Clean and reinstall dependencies if cache fails
      if: failure()
      run: |
        npm cache clean --force
        rm -rf node_modules
        npm ci
        echo 'Dependencies reinstalled after cache failure'
      shell: bash
