name: Git and GPG Setup
description: 'Set up GPG signed git bot'
inputs:
  name:
    description: 'GitHub Action Bot name'
    required: true
  email:
    description: 'GitHub bot email'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'

runs:
  using: "composite"
  steps:
    - name: Configure git for GitHub Actions Bot
      run: |
        git config --global user.name "${{ inputs.name }}"
        git config --global user.email "${{ inputs.email }}"
      shell: bash
