on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ hashFiles('package.json') }}-
            ${{ runner.OS }}-build-

      - run: npm install
      - run: npm run test

      # Step to check for inaccessible NuGet package
      - name: Check Unavailable NuGet Package
        uses: ./
        with:
          package: ${{ secrets.NUGET_NON_EXIST_PACKAGE }}
          version: ${{ secrets.NUGET_NON_EXIST_PACKAGE_VERSION }}
          attempts: 3
        continue-on-error: true

      # Step to check available NuGet package
      - name: Check Available NuGet Package
        uses: ./
        with:
          package: ${{ secrets.NUGET_EXIST_PACKAGE }}
          version: ${{ secrets.NUGET_EXIST_PACKAGE_VERSION }}
          attempts: 1
