# ./workflows/ci-code-test.yml
name: Cross-Platform Code Test CI

on:
  workflow_call:

jobs:
  code-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js, cache, and install dependencies
        timeout-minutes: 5
        uses: ./.github/actions/setup-node-project

      - name: Run lint
        run: npm run lint
        shell: bash

      - name: Run unit tests
        run: npm test
        shell: bash

      ## Code coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS
          verbose: true
          file: coverage/coverage-final.json
        continue-on-error: true

  security-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js, cache, and install dependencies
        timeout-minutes: 5
        uses: ./.github/actions/setup-node-project

      # Vulnerability check
      - name: Run npm audit
        run: npm audit --audit-level=high
        continue-on-error: true

      # License check
      - name: Install license checker
        run: npm install -g license-checker
        continue-on-error: true

      - name: Check licenses
        run: license-checker --summary --production
        continue-on-error: true
