name: Bundle CI

on:
  workflow_call:

jobs:
  bundle:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to access its content.
      - uses: actions/checkout@v4

      # Setup Node.js environment on the runner to match the node version used in development.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      # Cache node_modules based on hash of package.json and package-lock.json to speed up installations.
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('package.json', 'package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ hashFiles('package.json') }}-
            ${{ runner.OS }}-build-

      - name: Restore dependencies
        run: npm ci

      - name: Install ncc
        run: npm i -g @vercel/ncc

      ### Try to bundle & commit dist package.

      - name: Check for git changes
        id: check_changes
        run: |
          git add dist/index.js
          if git diff --staged --quiet; then
            echo "changes_exist=false" >> $GITHUB_OUTPUT
          else
            echo "changes_exist=true" >> $GITHUB_OUTPUT
          fi
        shell: sh

      - name: Commit updated version
        if: ${{ steps.check_changes.outputs.changes_exist == 'true' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "[GitHub Actions] Update dist/index.js"
          git push origin HEAD:${{ github.head_ref }} --force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
