name: Bundle CI

on:
  pull_request:
    branches:
      - main

jobs:
  bundle:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to access its content
      - uses: actions/checkout@v4

      # Setup Node.js environment on the runner to match the node version used in development.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      # Cache node_modules based on hash of package.json and package-lock.json to speed up installations.
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('package.json', 'package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ hashFiles('package.json') }}-
            ${{ runner.OS }}-build-

      - name: Restore Dependencies
        run: npm ci

      - name: Install ncc
        run: npm i -g @vercel/ncc

      # Bundle and commit dist package

      - name: Bundle Package
        run: npm run package

      - name: Commit updated version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add dist/index.js
          git commit -m "[GitHub Actions] Update dist/index.js"
          git push origin HEAD:${{ github.head_ref }} --force

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
