# ./workflows/ci.yml
name: CI

on:
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '.gitignore'
      - '.gitattributes'
      - '.github/dependabot.yml'
      - 'LICENSE'

  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '.gitignore'
      - '.gitattributes'
      - '.github/dependabot.yml'
      - 'LICENSE'

  workflow_dispatch:

jobs:
  code-test:
    uses: ./.github/workflows/ci-code-test.yml
    secrets: inherit

  create-bundle:
    needs: code-test
    uses: ./.github/workflows/ci-create-bundle.yml
    secrets: inherit

  action-test:
    needs: create-bundle
    uses: ./.github/workflows/ci-action-test.yml
    secrets: inherit
