name: CI

on:
  pull_request:
    branches:
      - main
      - dev

  push:
    branches:
      - main
      - dev

jobs:
  code-test:
    uses: ./.github/workflows/ci-code-test.yml
    secrets: inherit

  create-bundle:
    needs: code-test
    uses: ./.github/workflows/ci-create-bundle.yml
    secrets: inherit

  action-test:
    needs: create-bundle
    uses: ./.github/workflows/ci-action-test.yml
    secrets: inherit
